### ISSUE TITLE
options to filter acronyms that are used only a single time

### ISSUE THREAD

**Issue by indicatelovelace** [typst-community/glossarium#45]
Sometimes you need more control over when the first entry is printed.
For example, you use an acronym in a figure in short form, but still want the next appearance to be the long form. The Latex package solves this by providing a macro. I think something similar to that by adding another optional argument `ignore-use` could be useful.

I think an option for make-glossary to make the long form print for the first appearance optional would be great, too.

And last, I think options should be provided to filter acronyms that are used only a single time. I'm not sure on the details of this one yet though.

I can try to implement these myself, but I first wanted to hear your thoughts.

**Comment by quachpas** [comment]
Hello @indicatelovelace,
thanks for sharing your thoughts! 

> For example, you use an acronym in a figure in short form, but still want the next appearance to be the long form.
if you want to force the short-form you should be able to use
```typst
#gls(key, long: false) // short+suffix
```

> I think an option for make-glossary to make the long form print for the first appearance optional would be great, too.

I actually have a working version of this in my fork, but I haven't had the time to discuss this (I'll create an issue).

> And last, I think options should be provided to filter acronyms that are used only a single time. 

If by that, you mean counting the back-references to each acronym, then it is already possible using the internal API. Something like this maybe:
```typst
#import "@preview/glossarium:0.4.0": count-refs, __glossary_entries
#context {
    // All entries counts
    let entries = __glossary_entries.get()
    for (key, e) in entries {
      str(e.key) + " " + str(count-refs(e))
      linebreak()
    }
    linebreak()
    
    // Single-use
    let single_use_entries = entries.values().filter(e => count-refs(e) == 1)
    for e in single_use_entries {
      str(e.key) + " " + str(count-refs(e))
      linebreak()
    }
 }
 ``` 

If you have time, I think @slashformotion wouldn't refuse any contribution to the documentation or the user API!

**Comment by quachpas** [comment]
@indicatelovelace I will divert the issue of user control over first time usage or single usage to #57
