### ISSUE TITLE
Authorize a glossary entry with `short` or `long`

### ISSUE THREAD

**Issue by quachpas** [typst-community/glossarium#46]
`glossarium@0.4.1` requires the `short` attribute. We could relax this by allowing short or long (at least one of them). I have a WIP patch and I will ready a PR once I have merged the changes.

What do you think of changing this behaviour @slashformotion ?

**Comment by slashformotion** [comment]
Why not just put the "long" value in the "short" attribut ?

**Comment by quachpas** [comment]
IMO it's semantically more accurate to use `long` for long text, and `short` for acronyms, shorter words, e.g., I would find it weird that an entry for "climate change" is written as 
```typst
short: "climate change"
``` 
instead of 
```typst
long: "climate change"
``` 

More generally, entries that do not have corresponding short forms benefit from this.
