### ISSUE TITLE
Allow printing long only

### ISSUE THREAD

**Issue by jmigual** [typst-community/glossarium#51]
So, I usually like to write the long form only of a term in figures and places before it's "officially" introduced in the main text. E.g., 

```typst
#definition(gls("gosp", long:true))[We define the @gosp as the tuple ...]

#print-glossary(
  (
    (key: "gosp", short: "GOSP", long: "generic operation scheduling problem"),
  )
)
```

This should generate the text:

```txt
Definition 1 (generic operation scheduling problem): We define the generic operation 
scheduling problem (GOSP) as the tuple ...
```

TLDR: Can we have something similar to the `\acrlong` command in LaTeX glossaries?

**Comment by slashformotion** [comment]
you can write this:

```typ
#import "@preview/glossarium:0.4.1": *
#show: make-glossary

#let acrlong(ref) = {
  gls(ref, long: true)
}

We define the #acrlong("gosp") as the tuple ...

#print-glossary(
  (
    (key: "gosp", short: "GOSP", long: "generic operation scheduling problem"),
  )
)

```

**Comment by jmigual** [comment]
Hey! Thanks for your reply, unfortunately, this doesn't work because this still inserts the "(GOSP)" at the end of the long command. 

In the glossaries package of LaTeX the "acrlong" command always displays the long version without the short and it doesn't change the "first appearance" flag. So, if you type this in LaTeX:

```latex
\acrlong{gosp}

\gls{gosp}
```

You would get:

```
generic operation scheduling problem

generic operation scheduling problem (GOSP) 
```

This is the behavior I'm trying to recreate.

**Comment by jmigual** [comment]
I think I can fix it myself and make a PR with the change

**Comment by slashformotion** [comment]
I believe you could use the `gls-long` function to achieve what you want to do but it it only available on the master branch for now

**Comment by jmigual** [comment]
Yes! That's exactly what I was looking for. I guess I'll have to wait 😊

**Comment by quachpas** [comment]
@jmigual You can now use it with 0.4.2
