### ISSUE TITLE
dictionary key in `examples/full-example/main.typ`  is incorrect

### ISSUE THREAD

**Issue by jf---** [typst-community/glossarium#53]
in `0.4.1` entries use the keyword `desc` vs `description`, but for instance  `examples/full-example/main.typ` uses `description` which won't show up in the glossary.

```typst
    (
      key: "lod",
      short: "LOD",
      artshort: "an",
      long: "level of details",
      description: lorem(10),
    ),
```

```typst
    (
      key: "lod",
      short: "LOD",
      artshort: "an",
      long: "level of details",
      desc: lorem(10),
    ),
```

**Comment by quachpas** [comment]
Hello @jf--- !
If you are using version v0.4.1, you can take a look at the full example from this specific version https://github.com/typst-community/glossarium/blob/v0.4.1/examples/full-example/main.typ

The keys use the correct key `desc`.
