### ISSUE TITLE
`group` gets printed regardless of if the term is used.

### ISSUE THREAD

**Issue by TomVer99** [typst-community/glossarium#54]
The title is basically what the issue is.

If you have a term that is in a group, but that term is never used in the document the group heading still gets printed. This is an issue for me because I tend to have a single terms document in which I put all my project-related terms.

This issue also exists when there are multiple terms in a group, but none of those terms are used.

![image](https://github.com/user-attachments/assets/61844bc8-f800-4cd1-a294-0972c58331a8)
```
  (
    key: "unused",
    short: [UNUSED],
    long: [Unused],
    group: "unused"
  )
```

**Comment by TomVer99** [comment]
Using glossarium version `0.4.1` from `@preview`

**Comment by TomVer99** [comment]
Specifically in https://github.com/TomVer99/FHICT-typst-template/tree/main/examples/showcase. Template that is used is here: https://github.com/TomVer99/FHICT-typst-template/tree/main/template

**Comment by TomVer99** [comment]
I saw there should be some logic to prevent this in

https://github.com/typst-community/glossarium/blob/f55d66d4b0189586817350817a6fc6fc8f5701c9/themes/default.typ#L743-L746

Is this also present in `0.4.1`? Or just on the master branch for now?

**Comment by quachpas** [comment]
Hello @TomVer99, this feature is indeed present only in the master branch for now.

**Comment by quachpas** [comment]
@TomVer99 new release is out :)
