### ISSUE TITLE
(0.12-rc1) Unjustified glossary

### ISSUE THREAD

**Issue by fdekerme** [typst-community/glossarium#63]
When I added a Gloassary with Typst 0.11: 
![image](https://github.com/user-attachments/assets/9d59590c-8f7d-438b-bf00-a1406302b379)

but with 0.12-rc1, the glossary is no longer justified:

![image](https://github.com/user-attachments/assets/8a48809e-5d5f-42f2-8122-ef408def8f54)

**Comment by quachpas** [comment]
Thank you! It has been fixed in f9f8e8010bd5af8a672160453613a6b79323e985.
I will probably release it alongside 0.5.0

**Comment by PgBiel** [comment]
> Thank you! It has been fixed in f9f8e8010bd5af8a672160453613a6b79323e985.
> 
> I will probably release it alongside 0.5.0

By the way, you probably meant

`#show figure: set align(start)`

instead of `left`. This matters for text direction.

**Comment by quachpas** [comment]
Thanks @PgBiel! I missed that

**Comment by tfachada** [comment]
@quachpas Hey, I was wondering: do you count on releasing 0.5.0 before 0.12 gets out of beta?

**Comment by quachpas** [comment]
@tfachada I was thinking of releasing it soon-ish. Waiting a bit more in case I find more issues, or any other users raise a bug report.
